nuwa-source(){ echo $BASH_SOURCE ; }
nuwa-utils(){
  cat << EOU

       nuwa-genpkgdir 
           generate the nuwa-pkgdir function based on the output of "cmt show packages"

       nuwa-pkgdir <pkg>
           echo absolute path of the named package 
           ... the matching is done case-sensitively first and then with all lowercased 

       nuwa-cd                                      (this is aliased to "ncd" )
          cd to the directory obtained from nuwa-dir, arguments passed as is
          
       nuwa-dir  <pkg>[/aaa/bbb/etc] <sub>          (this is aliased to "nd" )
          echo absolute path according to argument specification...
          if the first argument contains a slash, the first element is
          interpreted as the CMT package ... which is used to lookup the absolute package directory, 
          the subsequent elements and the 2nd argument (if present) specify a subpath 
          within the project
            eg 
              nd gentools cmt
              nd gentools/cmt
              "$(nd rootiotest/tests)" == "/data/env/local/dyb/trunk_dbg/NuWa-trunk/dybgaudi/RootIO/RootIOTest/tests"

          NB this is just doing a case lookup... so it is very fast 

     TODO :
        also parse "cmt show projects" ... allowing to make more sense of the path 
        allowing for example the BUILD_PATH in .bash_profile to be derived from a project name

        factor out the cmt parsing ... 
            as it is in fact not nuwa specific and can be rehomed into cmt- for 
            usage in any cmt ensemble


        reposition the warning about no case function defined .. to when you want to use it
        rather than every new session




EOU



}


nuwa-env(){ 
   elocal- 
   local msg="=== $FUNCNAME :"
   local v=$(nuwa-version $*)
   if [ "$(nuwa-isinstalled $*)" == "NO" ]; then
      [ "$v" == "trunk" ] && echo $msg ABORT trunk is not installed .. infinite recursion avoidance && return 1
      echo $msg WARNING nuwa IS NOT installed based on "$*" OR NUWA_HOME : $NUWA_HOME , attempt fallback to trunk 
      nuwa- trunk
   else
      [ -z "$NUWA_NOFUNC" ] && nuwa-functions $*
      nuwa-exports $*   
      nuwa-defpkgdir
   fi

   
   
  
}



nuwa-first(){  echo $1 ; }
nuwa-second(){ echo $2 ; }
nuwa-third(){  echo $3 ; }
nuwa-lower() { echo $1 | tr "[:upper:]" "[:lower:]"  ; } 

nuwa-genpkgdir-(){

    
   local line
   echo "nuwa-pkgdir(){ "
   echo "## caution this function was generated by $BASH_SOURCE::$FUNCNAME on $(date) "
   echo "## based on \"cmt show packages\" performed from  $PWD "
   echo " case \$1 in "

   ## let correct case ... have first try    
   cmt show packages | while read line ; do
      nuwa-parse "$line"  
   done 

   ## then with case lowered 
   cmt show packages | while read line ; do
      nuwa-parse "$line"  lower
   done 

   echo "*) echo .  ;; "
   echo "esac "
   echo "} "
}


nuwa-parse(){
   local line="$1"
   local meth=$2

   local pkg=$(nuwa-first  $line)
   local lkg=$(nuwa-lower $pkg)
   local dir
   case $pkg in 
        VisRelease|DetRelease)  dir=$(nuwa-second  $line) ;; 
                            *)  dir=$(nuwa-third  $line)  ;; 
   esac

   ## keep absolute to work with CMTPROJECTPATH tethered layouts
   ## dir=${dir/$NUWA_HOME/}

   case $meth in 
     lower) [ "$lkg" != "$pkg" ] && echo   "$lkg) echo $dir/$pkg ;; "  ;;
         *) echo   "$pkg) echo $dir/$pkg ;; "  ;;
   esac  
}


nuwa-tmpdir(){  echo /tmp/env/${FUNCNAME/-*/}; }
nuwa-genpath(){ echo $(nuwa-tmpdir)/$FUNCNAME.gen.bash ; }
nuwa-genpkgdir(){
  local iwd=$PWD
  dyb__ dybgaudi/DybRelease/cmt
  local msg="=== $FUNCNAME :"
  local tmp=$(nuwa-tmpdir) && mkdir -p $tmp
  local gen=$(nuwa-genpath)
  [ ! -f "$gen" ] && echo $msg generating pkg to dir case statement based function nuwa-pkgdir && nuwa-genpkgdir- > $gen
  [   -f "$gen" ] && echo $msg sourcing $gen providing nuwa-pkgdir function ... delete this to regenerate
  . $gen
  cd $iwd
}

nuwa-defpkgdir(){
  local gen=$(nuwa-genpath)
  [ ! -f "$gen" ] &&  echo $msg $(nuwa-source) : ERROR you need to generate \"$gen\" which should contain the func nuwa-pkgdir with nuwa-genpkgdir && return 1
  . "$gen" 
}


nuwa-dir(){
  local arg=$1
  local pkg
  local sub
  ## arg contains a slash ... 
  if [ "${arg/\//}" != "$arg" ]; then
     pkg=${arg/\/*/}
     sub=${arg:$((${#pkg}+1))} 
     [ -n "$2" ] && sub="$sub/$2" 
 else
     pkg=${1:-DybRelease}
     sub=$2
  fi
  [ -z "$sub" ] &&  echo $(nuwa-pkgdir $pkg) || echo $(nuwa-pkgdir $pkg)/$sub
}
alias nd="nuwa-dir"


nuwa-cd(){
  cd $(nuwa-dir $*)
}
alias ncd="nuwa-cd"



nuwa-usage(){
  cat << EOU


   NB see also "nuwa-utils" for info on the tools "nd" "ncd" for jumping
      around from project to project 

   Versioning and placement control based on a single variable : NUWA_HOME

           NUWA_HOME              :  $NUWA_HOME
           nuwa-home-default      :  $(nuwa-home-default)

   
   If defined the NUWA_HOME must follow a standard layout for its last 2 levels, eg 
        /whatever/prefix/is/desired/1.0.0-rc02/NuWa-1.0.0-rc02
   if not defined a default is used


   Usage :
            nuwa-functions <v>
                source the dyb__.sh and slave.bash from for version v, defaulting to trunk 
                (equivalent to the former dyb-hookup )

            nuwa-info <v>
                dump the distro parameters for version v, defaulting to trunk 

            nuwa-exports <v>
                export convenience variables
                NB NUWA_HOME is never exported, that is regarded as an input only 

       
   Example of usage in .bash_profile :
   
        ## defines the nuwa- precursor , so must come before that 
        env-     
        
        ## comment the below two lines to use the default of "trunk"
        export NUWA_VERSION=1.0.0-rc02 ... used by dyb__version function for dybinst option setting 
        export NUWA_HOME=whatever/$NUWA_VERSION/NuWa-$NUWA_VERSION   ## NB prior to invoking "nuwa-" precursor 
        
        ## defines the functions and exports  
        nuwa-       
             
        ## setup a default location for operations : building/testing      
        export BUILD_PATH=dybgaudi/${nuwa_version:-trunk}/RootIO/RootIOTest
             
             
             
    To temporarily jump into another release :
        
        nuwa- 1.0.0-rc01          ( OR  trunk ) 
        nuwa-info    
        
     ## NB the dynamics will still be based using the version from NUWA_HOME, but the 
        exports and function paths should now show they hail from the chosen release
        


    THOUGHTS :
         nuwa- trunk
    
       tiz very useful to be able to use latest improvements to functions from trunk 
       while acting on behind the times releases ... so the functions should be 
       setup with this in mind, namely the envvar controlled version selection
       takes priority over the BASH_SOURCE determined one 
      



EOU

   nuwa-info


}

nuwa-dump(){

   nuwa-info
   nuwa-info trunk
   nuwa-info 1.0.0-rc01
   nuwa-info 1.0.0-rc02

}



nuwa-info(){
  local v=$1
  cat << EOI
  
   Dynamically derived quantities for version provided $v 
   If no version argument is given determine the quantities based
   in the value of  NUWA_HOME : $NUWA_HOME 
   
   NB unfortunately dyb__* functions have some dependency on NUWA_VERSION too
       NUWA_VERSION : $NUWA_VERSION  
   
   
   OR a default if that is not defined 
  
          nuwa-home $v    :  $(nuwa-home $v)
          nuwa-release $v :  $(nuwa-release $v)
          nuwa-version $v :  $(nuwa-version $v)
          nuwa-base $v    :  $(nuwa-base $v) 
          nuwa-scripts $v :  $(nuwa-scripts $v)  
          nuwa-dyb__ $v   :  $(nuwa-dyb__ $v)   
          nuwa-slave $v   :  $(nuwa-slave $v)  
  
          nuwa-ddr $v     :  $(nuwa-ddr $v)       
          nuwa-ddi $v     :  $(nuwa-ddi $v)        
          nuwa-ddt $v     :  $(nuwa-ddt $v)       
  
    Exported into environment :
        
            DYB : $DYB
            DDR : $DDR
            DDI : $DDI
            DDT : $DDT
            
            
    Source paths reported by the functions hooked up into the environment :
    
         dyb__source : $(dyb__source)
         slave-path  : $(slave-path) 
            
    Checking to see if nuwa for version \"$v\" is installed already based on existance of the dyb__.sh      
  
         nuwa-isinstalled $v : $(nuwa-isinstalled $v)
  
EOI
}




nuwa-home-default(){  echo $LOCAL_BASE/dyb/trunk_dbg/NuWa-trunk ; }

nuwa-home-construct(){
   local v=$1
   case $v in
      trunk) nuwa-home-default ;;
          *) echo $LOCAL_BASE/dyb/releases/$1/NuWa-$1 ;;
   esac       
}

nuwa-home(){          
  if [ "$1" == "" ]; then
     echo ${NUWA_HOME:-$(nuwa-home-default)}
  else 
     nuwa-home-construct $1 
  fi
}

nuwa-release(){       echo $(basename $(nuwa-home $*)); }
nuwa-version(){       local rel=$(nuwa-release $*) ; echo ${rel/NuWa-/} ; }
nuwa-scripts(){       echo installation/$(nuwa-version $*)/dybtest/scripts ; }
nuwa-base(){          echo $(dirname $(nuwa-home $*)) ; } 
nuwa-dyb__(){         echo $(nuwa-base $*)/$(nuwa-scripts $*)/dyb__.sh ; }
nuwa-slave(){         echo $(nuwa-base $*)/$(nuwa-scripts $*)/slave.bash ; }

nuwa-dyb(){           echo $(nuwa-base $*) ; } 
nuwa-ddr(){           echo $(nuwa-home $*) ; } 
nuwa-ddi(){           echo $(nuwa-base $*)/installation/$(nuwa-version $*)/dybinst/scripts ; }
nuwa-ddt(){           echo $(nuwa-base $*)/installation/$(nuwa-version $*)/dybtest ; }
nuwa-ddp(){           echo $(nuwa-home $*)/dybgaudi/DybPython/python/DybPython ; }
nuwa-ddx(){           echo $(nuwa-home $*)/tutorial/Simulation/SimHistsExample/tests ; }


nuwa-exports(){
   export DYB=$(nuwa-dyb $*)
   export DDT=$(nuwa-ddt $*)
   export DDP=$(nuwa-ddp $*)
   export DDI=$(nuwa-ddi $*)
   export DDR=$(nuwa-ddr $*)
   export DDX=$(nuwa-ddx $*)
}

nuwa-functions(){     
   
    local msg="=== $FUNCNAME : "
    local dyb__=$(nuwa-dyb__ $*)
    local slave=$(nuwa-slave $*)
    
    if [ -f $dyb__ ]; then
        set --
        . $dyb__
        [ -z $BASH_SOURCE ] && eval "function dyb__source(){  echo $dyb__ ; }"      ## workaround for older bash  
        dyb__default(){ echo dybgaudi/Simulation/GenTools ; } 
    else
        echo $msg no dyb__ $dyb__
    fi 
     
    if [ -f $slave ]; then
       . $slave
    else
       echo $msg no slave $slave 
    fi


}

nuwa-isinstalled(){
   nuwa-isinstalled- $* && echo YES || echo NO
}

nuwa-isinstalled-(){
    local dyb__=$(nuwa-dyb__ $*)
    [ -f "$dyb__" ] && return 0 || return 1
}
