
SOFLAGS     = -shared
CFLAGS      = -g -fno-common -Wall
LIBS        =
SOFIX       = so

#  rpm -ql pcre
#  rpm -ql pcre-devel


ifdef PCRE_INCDIR
PCRE_CFLAGS = -I$(PCRE_INCDIR)
else
PCRE_CFLAGS = -I/usr/include/pcre
endif

ifdef PCRE_LIBDIR
PCRE_LIBS   = -L$(PCRE_LIBDIR) -lpcre
else
PCRE_LIBS   = -L/usr/lib -lpcre
endif


#  rpm -ql glib2  
#  rpm -ql glib2-devel  
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
GLIB_LIBS   = -L/usr/lib -lglib-2.0


