
SOFLAGS     = -shared
CFLAGS      = -g -fno-common -Wall
LIBS        =
SOFIX       = so

#  rpm -ql pcre
#  rpm -ql pcre-devel
PCRE_CFLAGS = -I/usr/include/pcre 
PCRE_LIBS   = -L/usr/lib -lpcre

#  rpm -ql glib2  
#  rpm -ql glib2-devel  
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
GLIB_LIBS   = -L/usr/lib -lglib-2.0


