

dyw-osx-xcconfig(){
  local xcc=$DYW/g4dyb.xcconfig
  
  echo "//" > $xcc
  echo "// config file generated by env/dyw/dayabay.bash dyw-xcconfig " >> $xcc 
  echo "//" >> $xcc
  echo "//" >> $xcc
  echo "// below values based on the DYW_CMT variable " >> $xcc
  echo "//" >> $xcc
   
  for pair in $DYW_CMT
  do
	  echo $pair
	  name=`echo $pair | cut -f1 -d:`  
	  valu=`echo $pair | cut -f2 -d:`  
	  type=`echo $pair | cut -f3 -d:`  
	 
      echo "$name = $valu" >> $xcc
  done
  
  
  echo "//" >> $xcc
  echo "// below values based on the ENV2GUI_VARLIST  " >> $xcc
  echo "//" >> $xcc
  
  local env2gui_varlist=$(dyw-env2gui)
  for vname in $env2gui_varlist
  do
     eval valu=\$$vname
     echo "$vname = $valu" >> $xcc
  done
  
  echo ===== dyw-xcconfig created $xcc 
  cat $xcc
}



dyw-osx-env2gui(){
  echo $ENV2GUI_VARLIST | perl -ne 'print "$_\n" for(split(":"));' 
}


