

dyw-osx-xcconfig(){

  local name=g4dyb.xcconfig
  #local xcc=$DYW/G4dyb/cmt/g4dyb.xcconfig
  local xcc=$DYW/g4dyb.xcconfig
  
  echo "//" > $xcc
  echo "// config file generated by env/dyw/dyw-osx.bash dyw-osx-xcconfig " >> $xcc 
  echo "//" >> $xcc
  echo "//" >> $xcc
  echo "// below values based on the DYW_CMT variable " >> $xcc
  echo "//" >> $xcc
   
  for pair in $DYW_CMT
  do
	  echo $pair
	  name=`echo $pair | cut -f1 -d:`  
	  valu=`echo $pair | cut -f2 -d:`  
	  type=`echo $pair | cut -f3 -d:`  
	 
      ## replace commas with spaces ... 
      valu=$(echo $valu | perl -p -e 's/,/ /g')
     
      echo "$name = $valu" >> $xcc
  done
  
  
  echo "//" >> $xcc
  echo "// below values based on the ENV2GUI_VARLIST  " >> $xcc
  echo "//" >> $xcc
  
  local env2gui_varlist=$(dyw-osx-env2gui)
  for vname in $env2gui_varlist
  do
     eval valu=\$$vname
     echo "$vname = $valu" >> $xcc
  done
  
  echo ===== dyw-osx-xcconfig created $xcc 
  cat $xcc
}



dyw-osx-env2gui(){
  echo $ENV2GUI_VARLIST | perl -ne 'print "$_\n" for(split(":"));' 
}



# trying to automate adding to Xcode fails... 
#
#   set new_file to make new file reference with properties {name:file_name, file encoding:macos roman, full path:full_file_path}
#
# the below succeeds to add the reference ... but attempting to view the file results in cannot find the file 
#
# set itemName to "g4dyb.xcconfig"
# tell application "Xcode"
#	tell group "cmt" of group "G4dyb" of group "Source" of project "legacy-blyth"
#		make new file reference with properties {name:itemName, path:itemName, path type:group relative}
#	end tell
# end tell
#
#  app(u'/Developer/Applications/Xcode.app').projects['legacy-blyth'].groups['Source'].groups['G4dyb'].groups['cmt'].make(new=k.file_reference, with_properties={k.path: 'g4dyb.xcconfig', k.name: 'g4dyb.hh', k.path_type: k.group_relative})
#
#


