

MODJK_NAME=tomcat-connectors-1.2.22-src
MODJK_DIST=http://ftp.kddilabs.jp/infosystems/apache/tomcat/tomcat-connectors/jk/source/jk-1.2.22
MODJK_NIK=mod_jk

modjk-ctx(){

   tag=${1:-$MODJK_NAME} 
   nik=$MODJK_NIK
   nam=$tag
   tgz=$nam.tar.gz
   url=$MODJK_DIST/$tgz

   [ -d $LOCAL_BASE/$nik  ] || ( cd $LOCAL_BASE && sudo mkdir -p $nik && sudo chown -R $USER $nik )
   cd $LOCAL_BASE/$nik

}


modjk-get(){
   modjk-ctx $*
   [ -f $tgz ] || curl -o $tgz $url
   [ -d $nam ] || tar zxvf $tgz 
}

modjk-configure(){
   modjk-ctx $*
   cd $nam/native 
   ./configure --with-apxs=$APACHE2_HOME/sbin/apxs 
}

modjk-make(){
   modjk-ctx $*
   cd $nam/native 
   make

   ##libtool: install: warning: remember to run `libtool --finish /usr/local/apache2/httpd-2.0.59/libexec'
}

modjk-place(){
   modjk-ctx $*
   cd $nam/native 

   place=$APACHE2_HOME/libexec/mod_jk.so
   [ -f $place ] && echo $place is already present || ( sudo cp apache-2.0/mod_jk.so $place  && sudo chmod ugo+x $place )
   ls -alst $APACHE2_HOME/libexec
}



modjk-setup(){

  cd $APACHE2_HOME/etc/apache2

  if [ $(id -u) == $(stat -f%u .) ]; then

      apache2-add-module jk
      modjk-umbrella           > umbrella.conf
      
	  workers=$(exist-lookup workers)
      modjk-workers-properties "$workers"  > workers.properties 
	  cat workers.properties

      for worker in $workers
	  do	  
         exist-jkmount $worker  > $worker.conf 
         echo "Include etc/apache2/$worker.conf" >> umbrella.conf
		 cat $worker.conf
	  done	 
	  cat umbrella.conf

	  modjk-connect 
  else 
	  sudo bash -lc modjk-setup       ## if dont own the folder, come back as root  
  fi	  
}

modjk-umbrella(){

cat << EOU
#
# sourced from modjk-umbrella
#
<IfModule mod_jk.c>

   JkWorkersFile etc/apache2/workers.properties
   JkLogFile     var/apache2/log/mod_jk.log
   
# Set the jk log level [debug/error/info] and format
#  debug is extreme   
   JkLogLevel   info 
   JkLogStampFormat "[%a %b %d %H:%M:%S %Y] "
   JkOptions     +ForwardKeySize +ForwardURICompat -ForwardDirectories
   JkRequestLogFormat     "%w %V %T"

# http://publib.boulder.ibm.com/iseries/v5r2/ic2924/info/rzaie/rzaiemod_jk.htm
# exact , context or suffix matching 

   <Location /*/WEB-INF/*>
      AllowOverride None
      deny from all
   </Location>

   <Location /*/META-INF/*>
      AllowOverride None
      deny from all
   </Location>


</IfModule>


EOU
}

modjk-workers-properties(){

  workers=${1:-dummyworkers}

cat << EOH
#
#   this was generated by modjk-workers-properties
#
workers.tomcat_home=$TOMCAT_HOME
workers.java_home=$JAVA_HOME
worker.list=$(echo $workers | perl -pe 's/ /,/g')
EOH

for worker in $workers
do	
   jkport=$(exist-lookup jkport $worker)
   modjk-worker $worker $jkport
done
}

modjk-worker(){
   name=${1:-dummyworker}
   port=${2:-dummyport}
cat << EOW
worker.$name.type=ajp13
worker.$name.host=localhost
worker.$name.port=$port
worker.$name.socket_keepalive=1
EOW
}

modjk-connect(){
   cd $APACHE2_HOME/etc/apache2
   grep etc/apache2/umbrella.conf  httpd.conf || echo Include etc/apache2/umbrella.conf >> httpd.conf 
   tail -10 httpd.conf
}


