//
//    .L MyMain.C
//    
//
//
//
// 
// File: MyMain.h

#include <TGClient.h>
#include <TGButton.h>

#include <TGMenu.h>
#include <TGFrame.h>
#include <TGDockableFrame.h>
#include <TGCanvas.h>


#include <TCanvas.h>

enum ETestCommandIdentifiers {
   M_FILE_OPEN
   };


class MyMainFrame : public TGMainFrame {
private:

   TGDockableFrame    *fMenuDock;
   TGCanvas           *fCanvasWindow;
   TGMenuBar          *fMenuBar;
   TGPopupMenu        *fMenuFile;
   TGLayoutHints      *fMenuBarLayout, *fMenuBarItemLayout, *fMenuBarHelpLayout;


    TGTextButton    *fButton1, *fButton2;
    TGPictureButton *fPicBut;
    TGCheckButton   *fChkBut;
    TGRadioButton   *fRBut1, *fRBut2;
    TGLayoutHints   *fLayout;
public:
    MyMainFrame(const TGWindow *p, UInt_t w, UInt_t h);
    ~MyMainFrame() { } // need to delete here created widgets
    Bool_t ProcessMessage(Long_t msg, Long_t parm1, Long_t parm2);
};


// File: MyMain.cxx
// #include "MyMain.h"

MyMainFrame::MyMainFrame(const TGWindow *p, UInt_t w, UInt_t h)
    : TGMainFrame(p, w, h)
{
    // Create a main frame with a number of different buttons.


   fMenuDock = new TGDockableFrame(this);
   AddFrame(fMenuDock, new TGLayoutHints(kLHintsExpandX, 0, 0, 1, 0));
   fMenuDock->SetWindowName("GuiTest Menu");

   fMenuBarLayout = new TGLayoutHints(kLHintsTop | kLHintsExpandX);
   fMenuBarItemLayout = new TGLayoutHints(kLHintsTop | kLHintsLeft, 0, 4, 0, 0);
   fMenuBarHelpLayout = new TGLayoutHints(kLHintsTop | kLHintsRight);

   fMenuFile = new TGPopupMenu(fClient->GetRoot());
   fMenuFile->AddEntry("&Open...", M_FILE_OPEN);


   // Menu button messages are handled by the main frame (i.e. "this")
   // ProcessMessage() method.
   fMenuFile->Associate(this);

    fMenuBar = new TGMenuBar(fMenuDock, 1, 1, kHorizontalFrame);
   fMenuBar->AddPopup("&File", fMenuFile, fMenuBarItemLayout);
   
    fMenuDock->AddFrame(fMenuBar, fMenuBarLayout);




    fButton1 = new TGTextButton(this, "&Version", 1);
    fButton1->SetCommand("printf(\"This is ROOT version %s\\n\","
                          "gROOT->GetVersion());");
    fButton2 = new TGTextButton(this, "&Exit", 2);
    fButton2->SetCommand(".q" );
    fPicBut = new TGPictureButton(this, gClient->GetPicture("world.xpm"), 3);
    fPicBut->SetCommand("printf(\"hello world!\\n\");");
    fChkBut = new TGCheckButton(this, "Check Button", 4);
    fRBut1 = new TGRadioButton(this, "Radio Button 1", 5);
    fRBut2 = new TGRadioButton(this, "Radio Button 2", 6);
    fLayout = new TGLayoutHints(kLHintsCenterX | kLHintsCenterY);
    AddFrame(fButton1, fLayout);
    AddFrame(fPicBut, fLayout);
    AddFrame(fButton2, fLayout);
    AddFrame(fChkBut, fLayout);
    AddFrame(fRBut1, fLayout);
    AddFrame(fRBut2, fLayout);
    MapSubwindows();
    Layout();
    SetWindowName("Button Example");
    SetIconName("Button Example");
    MapWindow();
}


// Continuation of MyMain.cxx

Bool_t MyMainFrame::ProcessMessage(Long_t msg, Long_t parm1, Long_t)
{
    // Process events generated by the buttons in the frame.
    switch (GET_MSG(msg)) {
        case kC_COMMAND:
            switch (GET_SUBMSG(msg)) {
                case kCM_BUTTON:
                    printf("text button id %ld pressed\n", parm1);
                    break;
                case kCM_CHECKBUTTON:
                    printf("check button id %ld pressed\n", parm1);
                    break;
                case kCM_RADIOBUTTON:
                    if (parm1 == 5)
                        fRBut2->SetState(kButtonUp);
                    if (parm1 == 6)
                        fRBut1->SetState(kButtonUp);
                    printf("radio button id %ld pressed\n", parm1);
                    break;
                default:
                    break;
            }
        default:
            break;
    }
    return kTRUE;
}


