/*
   This is based on 
       $ROOTSYS/tutorials/eve/alice_esd_split.C
   see the introductory text there


   Handy one liners for debugging from cint :
      AliEvReader* aer = (AliEvReader*)EvReader::GetEvReader(EvReader::kAlice);


    aer->esd_tree->GetUserInfo()->ls()
OBJ: TList      TList   Doubly linked list 
 OBJ: AliESDEvent       AliESDEvent     Generated by MakeProject. : 0 at: 


    root [8] esd->fESDObjects 

 *** Break *** segmentation violation
(no debugging symbols found)
Using host libthread_db library "/lib/tls/libthread_db.so.1".
Attaching to program: /proc/2757/exe, process 2757
(no debugging symbols found)...done.
[Thread debugging using libthread_db enabled]
[New Thread -1208973632 (LWP 2757)]
(no debugging symbols found)...done.
(no debugging symbols found)...done.
(no debugging symbols found)...done.






root [8]  TIter next(esd->fESDObjects);
root [9]  TObject *el
root [10] while ((el=(TNamed*)next())) cout << el->GetName() << endl 
AliESDRun
AliESDHeader
AliESDZDC
AliESDFMD
AliESDVZERO
AliESDTZERO
SPDVertex
PrimaryVertex
AliMultiplicity
PHOSTrigger
EMCALTrigger
Tracks
MuonTracks
PmdTracks
TrdTracks
V0s
Cascades
Kinks
CaloClusters
AliRawDataErrorLogs
AliESDfriend




*/

R__EXTERN TEveProjectionManager *gRPhiMgr;
R__EXTERN TEveProjectionManager *gRhoZMgr;
TEveGeoShape *gGeoShape;
TGTextEntry *gTextEntry;
TGHProgressBar *gProgress;


// it seems these need to be global ???
TFile* esd_file          = 0;
TFile* esd_friends_file  = 0;
TTree* esd_tree          = 0 ; 


//______________________________________________________________________________
void alice_esd_split()
{

   gROOT->ProcessLine(".x EvReader.C");
   gROOT->ProcessLine(".x AliEvReader.C");

   IEvReader* er = EvReader::GetEvReader();
   er->InitProject( AliEvReader::esd_file_name , AliEvReader::project_name );

   gROOT->ProcessLine(".x EvNav.C");
   gROOT->ProcessLine(".x EvDisp.C");
   EvDisp* evd = EvDisp::GetEvDisp();

   gROOT->ProcessLine(".x evd_geometry.C");
   
   evd->make_gui();
   evd->import_projection_geometry();
   evd->load_event();
   evd->update_projections();

   gEve->Redraw3D(kTRUE); // Reset camera after the first event has been shown.
}


