# OPEN ROOT file at the very beginning
####  Output File Name
#/files/output dybsim.root

## Select detector optical property input file or adopt the default. 
## E.g. FileName = MaterialPropertiesFile
## <FileName> must be a tag in the file xml/control.xml and 
## it's a child element of <controlParameters>   
## /dyw/detector/input <FileName>

####  select detector:
#     "Prototype" for IHEP prototype.
#     "SingleModule" for Daya Bay 20 ton detector.
#/dyw/detector/select SingleModule 
/dyw/detector/select NearSitePool

#### Do NOT touch the following line.
/run/initialize 

####  Control the verbose
#     verbose level: 0: the least printout, 2: most detailed information.
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/dyw/phys/verbose 0 

####  Control the PMT Optical Model
#     verbose level :  0: quiet;
#                      1: minimal entrance/exit info;
#                      2: +print verbose tracking info;
#                      >=10:  lots of info on thin photocathode calcs.
#     luxlevel: 0: No transmitting and relfection on photocathode.
#               1: A simple model for transmitting and reflection.
#               >=2: Full PMT optical model. The default value is 3.
/PMTOpticalModel/verbose 0
/PMTOpticalModel/luxlevel 3

##### Physics process
/process/list
# /process/inactivate Cerenkov

####  Set scinitillation yield of the liquid Scintillator .
#     GdLS is for Gd-doped LS and LS is for normal LS in gamma catcher.
/dyw/detector/ScintYield_GdLS 9000.0 
/dyw/detector/ScintYield_LS 9000.0 

####  Visulization
#/control/execute vis.mac

####  Select event Generator
#     Single: Use single particle generator of Geant4, parameters are 
#             determined by /gun/ settings, and the genfile is invalid.
#     Standalone: read generated events from a root file specified by 
#             /dyw/generator/genfile, the /gun/ setting is invalid.

#### Generator Option 1, should comment out the option 2.
#/dyw/generator/select Single
#/gun/particle gamma 
#/gun/energy 1 MeV

#/gun/position 0 0 0 cm      
# from Raymond Tsang... center of neutron detector at (0,0,-620) mm
#/gun/position 0 0 -62 cm      



#### Number of Events to simulate.
#/run/beamOn 1
