# generate 100 e- at center of single module detector
# 31aug06 djaffe
#
# OPEN ROOT file at the very beginning
####  Output File Name
/files/output test-optical.root

## Select detector optical property input file or adopt the default. 
## E.g. FileName = MaterialPropertiesFile
## <FileName> must be a tag in the file xml/control.xml and 
## it's a child element of <controlParameters>   
## /dyw/detector/input <FileName>

####  select detector:
#     "Prototype" for IHEP prototype.
#     "SingleModule" for Daya Bay 20 ton detector.
/dyw/detector/select SingleModule

#### Do NOT touch the following line.
/run/initialize 

####  Control the verbose
#     verbose level: 0: the least printout, 2: most detailed information.
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/dyw/phys/verbose 0 

####  Control the PMT Optical Model
#     verbose level :  0: quiet;
#                      1: minimal entrance/exit info;
#                      2: +print verbose tracking info;
#                      >=10:  lots of info on thin photocathode calcs.
#     luxlevel: 0: No transmitting and relfection on photocathode.
#               1: A simple model for transmitting and reflection.
#               >=2: Full PMT optical model. The default value is 3.
/PMTOpticalModel/verbose 0
/PMTOpticalModel/luxlevel 3

##### Physics process
/process/list
# /process/inactivate Cerenkov

####  Set scinitillation yield of the liquid Scintillator .
#     GdLS is for Gd-doped LS and LS is for normal LS in gamma catcher.
/dyw/detector/ScintYield_GdLS 0
/dyw/detector/ScintYield_LS 0

#### Generator Option 1, should comment out the option 2.
#/dyw/generator/select Single
/dyw/generator/select Generator2
/dyw/generator2/main GenericGun

/gun/particle opticalphoton
/gun/energy 3 eV
/gun/position 0 0 0 m

## direction is overridden when using "Single" so use "Generator2" and "GenericGun" but then need to implement the polariztion stuff 
/gun/direction 1 1 0 

# -360 or comment out to make random
/dyw/generator2/optPhotonPol 90 deg 

# The command below allows one to generate particle uniformly in Gd-LS volume 
# /dyw/generator2/pos glg4 0 0 3000 fill World GdLiquidScintillator
#
# Or you could use below to generate particle from a single point, unit = mm
/dyw/generator2/pos glg4 0 0 0 



/control/execute set-scene.mac



#### Number of Events to simulate.
/run/beamOn 10

